export interface TemplateConfig {
  layoutStyle: "single-column" | "two-column" | "left-sidebar" | "right-sidebar";
  fontFamily: "sans" | "serif" | "mono" | "montserrat" | "playfair" | "outfit";
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  borderRadius: "none" | "sm" | "md" | "lg";
  sectionSpacing: "compact" | "normal" | "spacious";
  dividerStyle: "none" | "solid" | "dashed" | "bold" | "double";
  iconStyle: "none" | "simple" | "circle" | "square";
  headerStyle: "minimal" | "split" | "banner" | "compact" | "left-border";
  skillStyle: "text" | "badges" | "progress" | "dots" | "stars" | "categories";
  photoStyle: "none" | "circle" | "rounded-square" | "square";
  photoPosition: "left" | "right" | "center";
  timelineStyle: "none" | "solid" | "dashed";
  pageMargin: "compact" | "normal" | "wide";
  fontSize: "sm" | "base" | "lg";
  lineHeight: "tight" | "normal" | "loose";
}

export interface ResumeTemplateItem {
  id: string;
  name: string;
  slug: string;
  category: "ATS Friendly" | "Modern" | "Minimal" | "Professional" | "Executive" | "Creative" | "Academic";
  description: string;
  atsScore: number;
  popularity: number;
  recommendedFor: string[];
  isPremium: boolean;
  defaultConfig: TemplateConfig;
}

export const templatesRegistry: ResumeTemplateItem[] = [
  {
    id: "ats-friendly",
    name: "ATS Friendly Classic",
    slug: "ats-friendly",
    category: "ATS Friendly",
    description: "Highly optimized single-column layout using standard fonts, designed to pass parsing systems with maximum scores.",
    atsScore: 99,
    popularity: 5.0,
    recommendedFor: ["Tech", "Finance", "Healthcare", "Corporate Roles"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "sans",
      primaryColor: "#18181b",
      secondaryColor: "#71717a",
      accentColor: "#3f3f46",
      backgroundColor: "#ffffff",
      borderRadius: "none",
      sectionSpacing: "compact",
      dividerStyle: "solid",
      iconStyle: "none",
      headerStyle: "compact",
      skillStyle: "text",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "sm",
      lineHeight: "normal",
    },
  },
  {
    id: "modern",
    name: "Modern Elegant",
    slug: "modern",
    category: "Modern",
    description: "Clean sans-serif structure, modern sidebar accent details, perfect for tech and operations roles.",
    atsScore: 92,
    popularity: 4.8,
    recommendedFor: ["Software Engineering", "Product Design", "Operations"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "sans",
      primaryColor: "#4f46e5",
      secondaryColor: "#4b5563",
      accentColor: "#818cf8",
      backgroundColor: "#ffffff",
      borderRadius: "md",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "circle",
      headerStyle: "split",
      skillStyle: "badges",
      photoStyle: "circle",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "minimal",
    name: "Minimalist Clean",
    slug: "minimal",
    category: "Minimal",
    description: "Utmost simplicity, focused heavily on type readability and whitespace spacing layouts.",
    atsScore: 95,
    popularity: 4.7,
    recommendedFor: ["Writing", "Consulting", "Executive Assistants"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "sans",
      primaryColor: "#111827",
      secondaryColor: "#6b7280",
      accentColor: "#374151",
      backgroundColor: "#ffffff",
      borderRadius: "none",
      sectionSpacing: "normal",
      dividerStyle: "none",
      iconStyle: "none",
      headerStyle: "minimal",
      skillStyle: "text",
      photoStyle: "none",
      photoPosition: "center",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "professional",
    name: "Professional Corporate",
    slug: "professional",
    category: "Professional",
    description: "Traditional corporate alignment, left border highlights, and conservative gray highlights.",
    atsScore: 97,
    popularity: 4.9,
    recommendedFor: ["Finance", "Sales", "Legal", "General Business"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "serif",
      primaryColor: "#1e3a8a",
      secondaryColor: "#475569",
      accentColor: "#3b82f6",
      backgroundColor: "#ffffff",
      borderRadius: "sm",
      sectionSpacing: "normal",
      dividerStyle: "bold",
      iconStyle: "simple",
      headerStyle: "left-border",
      skillStyle: "text",
      photoStyle: "square",
      photoPosition: "right",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "executive",
    name: "Executive Bold",
    slug: "executive",
    category: "Executive",
    description: "Elegant serif typography, split layout timeline nodes, designed for leadership positions.",
    atsScore: 90,
    popularity: 4.9,
    recommendedFor: ["Directors", "VPs", "C-Suite Executives", "Managers"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "two-column",
      fontFamily: "outfit",
      primaryColor: "#0f172a",
      secondaryColor: "#64748b",
      accentColor: "#38bdf8",
      backgroundColor: "#ffffff",
      borderRadius: "md",
      sectionSpacing: "spacious",
      dividerStyle: "solid",
      iconStyle: "square",
      headerStyle: "split",
      skillStyle: "stars",
      photoStyle: "rounded-square",
      photoPosition: "left",
      timelineStyle: "solid",
      pageMargin: "wide",
      fontSize: "base",
      lineHeight: "loose",
    },
  },
  {
    id: "corporate",
    name: "Corporate Slate",
    slug: "corporate",
    category: "Professional",
    description: "Elegant professional format utilizing slate panels, ideal for engineering management and accounting.",
    atsScore: 96,
    popularity: 4.6,
    recommendedFor: ["Accounting", "Engineering Management", "HR Manager"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "serif",
      primaryColor: "#334155",
      secondaryColor: "#64748b",
      accentColor: "#475569",
      backgroundColor: "#ffffff",
      borderRadius: "sm",
      sectionSpacing: "normal",
      dividerStyle: "double",
      iconStyle: "none",
      headerStyle: "split",
      skillStyle: "badges",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "software-engineer",
    name: "Software Engineer Pro",
    slug: "software-engineer",
    category: "Modern",
    description: "Tech-focused outline with dark codes styling details, highlight link widgets, and programming categories.",
    atsScore: 94,
    popularity: 4.95,
    recommendedFor: ["Software Engineers", "Backend Devs", "System Admins", "QA Engineers"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "mono",
      primaryColor: "#06b6d4",
      secondaryColor: "#94a3b8",
      accentColor: "#0891b2",
      backgroundColor: "#0f172a", // Dark Mode Resume layout default!
      borderRadius: "md",
      sectionSpacing: "compact",
      dividerStyle: "dashed",
      iconStyle: "simple",
      headerStyle: "left-border",
      skillStyle: "categories",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "dashed",
      pageMargin: "compact",
      fontSize: "sm",
      lineHeight: "normal",
    },
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    slug: "data-scientist",
    category: "Modern",
    description: "Left sidebar splitting, highlights technical research, achievements lists, and metrics progress bars.",
    atsScore: 91,
    popularity: 4.75,
    recommendedFor: ["Data Scientists", "ML Engineers", "Research Leads", "Data Analysts"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "left-sidebar",
      fontFamily: "montserrat",
      primaryColor: "#0f766e",
      secondaryColor: "#4b5563",
      accentColor: "#14b8a6",
      backgroundColor: "#ffffff",
      borderRadius: "md",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "square",
      headerStyle: "split",
      skillStyle: "progress",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "solid",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "product-manager",
    name: "Product Manager Pro",
    slug: "product-manager",
    category: "Modern",
    description: "Right sidebar layout displaying product achievements, core badges metrics, and summary banners.",
    atsScore: 93,
    popularity: 4.85,
    recommendedFor: ["Product Managers", "Project Managers", "Agile Coaches"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "right-sidebar",
      fontFamily: "outfit",
      primaryColor: "#b91c1c",
      secondaryColor: "#4b5563",
      accentColor: "#ef4444",
      backgroundColor: "#ffffff",
      borderRadius: "lg",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "circle",
      headerStyle: "banner",
      skillStyle: "badges",
      photoStyle: "circle",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "designer",
    name: "Creative Designer Portfolio",
    slug: "designer",
    category: "Creative",
    description: "Gradient top header, circular bordered profile picture, creative purple accents, and visual ratings.",
    atsScore: 84,
    popularity: 4.9,
    recommendedFor: ["UX Designers", "Graphic Designers", "Art Directors", "Illustrators"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "two-column",
      fontFamily: "playfair",
      primaryColor: "#7c3aed",
      secondaryColor: "#6b7280",
      accentColor: "#a78bfa",
      backgroundColor: "#fbfbfe",
      borderRadius: "lg",
      sectionSpacing: "spacious",
      dividerStyle: "none",
      iconStyle: "circle",
      headerStyle: "split",
      skillStyle: "stars",
      photoStyle: "circle",
      photoPosition: "center",
      timelineStyle: "dashed",
      pageMargin: "normal",
      fontSize: "lg",
      lineHeight: "loose",
    },
  },
  {
    id: "marketing",
    name: "Marketing & Growth",
    slug: "marketing",
    category: "Creative",
    description: "Vibrant layout with right sidebar, progress bar ratings, and bold summary typography headings.",
    atsScore: 88,
    popularity: 4.7,
    recommendedFor: ["Marketing Managers", "Growth Hackers", "SEO Specialists", "PR Leads"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "right-sidebar",
      fontFamily: "montserrat",
      primaryColor: "#db2777",
      secondaryColor: "#4b5563",
      accentColor: "#f472b6",
      backgroundColor: "#ffffff",
      borderRadius: "md",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "simple",
      headerStyle: "banner",
      skillStyle: "progress",
      photoStyle: "rounded-square",
      photoPosition: "right",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "finance",
    name: "Finance & Accounting",
    slug: "finance",
    category: "Professional",
    description: "Very strict traditional formatting, tiny margins, and standard black text indicators.",
    atsScore: 98,
    popularity: 4.8,
    recommendedFor: ["Financial Analysts", "Auditors", "CPAs", "Investment Bankers"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "serif",
      primaryColor: "#111827",
      secondaryColor: "#374151",
      accentColor: "#4b5563",
      backgroundColor: "#ffffff",
      borderRadius: "none",
      sectionSpacing: "compact",
      dividerStyle: "solid",
      iconStyle: "none",
      headerStyle: "compact",
      skillStyle: "text",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "compact",
      fontSize: "sm",
      lineHeight: "tight",
    },
  },
  {
    id: "medical",
    name: "Medical CV Layout",
    slug: "medical",
    category: "Professional",
    description: "Clean spacing outline with extensive sections for credentials, licensing, certifications, and listings.",
    atsScore: 95,
    popularity: 4.65,
    recommendedFor: ["Physicians", "Nurses", "Med Students", "Clinical Staff"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "sans",
      primaryColor: "#0d9488",
      secondaryColor: "#4b5563",
      accentColor: "#2dd4bf",
      backgroundColor: "#ffffff",
      borderRadius: "sm",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "simple",
      headerStyle: "left-border",
      skillStyle: "text",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "academic-cv",
    name: "Academic CV",
    slug: "academic-cv",
    category: "Academic",
    description: "Multipage structural layout designed for research publications, teaching history, and grants lists.",
    atsScore: 94,
    popularity: 4.7,
    recommendedFor: ["Professors", "Researchers", "Ph.D. Candidates"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "serif",
      primaryColor: "#111827",
      secondaryColor: "#374151",
      accentColor: "#4b5563",
      backgroundColor: "#ffffff",
      borderRadius: "none",
      sectionSpacing: "normal",
      dividerStyle: "bold",
      iconStyle: "none",
      headerStyle: "minimal",
      skillStyle: "text",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "wide",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "research-cv",
    name: "Scientific Research",
    slug: "research-cv",
    category: "Academic",
    description: "Clean monospace parameters highlighting laboratory projects, patents, and references indexes.",
    atsScore: 92,
    popularity: 4.5,
    recommendedFor: ["Lab Technicians", "Data Researchers", "Biologists"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "mono",
      primaryColor: "#1e293b",
      secondaryColor: "#475569",
      accentColor: "#64748b",
      backgroundColor: "#ffffff",
      borderRadius: "none",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "none",
      headerStyle: "compact",
      skillStyle: "text",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "sm",
      lineHeight: "normal",
    },
  },
  {
    id: "graduate",
    name: "IIT/NIT Graduate",
    slug: "graduate",
    category: "Academic",
    description: "Compact academic spacing drawing student achievements, credentials, coursework, and projects first.",
    atsScore: 96,
    popularity: 4.8,
    recommendedFor: ["College Seniors", "Tech Graduates", "Engineering Students"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "montserrat",
      primaryColor: "#2563eb",
      secondaryColor: "#4b5563",
      accentColor: "#3b82f6",
      backgroundColor: "#ffffff",
      borderRadius: "sm",
      sectionSpacing: "compact",
      dividerStyle: "solid",
      iconStyle: "circle",
      headerStyle: "split",
      skillStyle: "badges",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "compact",
      fontSize: "sm",
      lineHeight: "normal",
    },
  },
  {
    id: "college-student",
    name: "College Entry-Level",
    slug: "college-student",
    category: "Academic",
    description: "Perfect single page layout prioritizing coursework, academic lists, and coding skills.",
    atsScore: 97,
    popularity: 4.75,
    recommendedFor: ["Freshers", "Undergrads", "High School Students"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "outfit",
      primaryColor: "#4f46e5",
      secondaryColor: "#4b5563",
      accentColor: "#6366f1",
      backgroundColor: "#ffffff",
      borderRadius: "md",
      sectionSpacing: "compact",
      dividerStyle: "solid",
      iconStyle: "circle",
      headerStyle: "compact",
      skillStyle: "badges",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "sm",
      lineHeight: "normal",
    },
  },
  {
    id: "internship",
    name: "Internship Starter",
    slug: "internship",
    category: "Academic",
    description: "Highlights key projects and university courses, designed to attract entry-level hiring managers.",
    atsScore: 95,
    popularity: 4.7,
    recommendedFor: ["Summer Internships", "Co-op Placements"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "sans",
      primaryColor: "#2563eb",
      secondaryColor: "#4b5563",
      accentColor: "#60a5fa",
      backgroundColor: "#ffffff",
      borderRadius: "md",
      sectionSpacing: "compact",
      dividerStyle: "solid",
      iconStyle: "simple",
      headerStyle: "split",
      skillStyle: "badges",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "sm",
      lineHeight: "normal",
    },
  },
  {
    id: "creative",
    name: "Vibrant Creative",
    slug: "creative",
    category: "Creative",
    description: "Creative styling nodes using purple side columns, stars ratings, and timeline nodes.",
    atsScore: 82,
    popularity: 4.85,
    recommendedFor: ["Actors", "Creative Writers", "Content Creators", "PR Leads"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "two-column",
      fontFamily: "outfit",
      primaryColor: "#6d28d9",
      secondaryColor: "#4b5563",
      accentColor: "#8b5cf6",
      backgroundColor: "#faf5ff",
      borderRadius: "lg",
      sectionSpacing: "spacious",
      dividerStyle: "none",
      iconStyle: "circle",
      headerStyle: "split",
      skillStyle: "stars",
      photoStyle: "circle",
      photoPosition: "left",
      timelineStyle: "dashed",
      pageMargin: "normal",
      fontSize: "lg",
      lineHeight: "loose",
    },
  },
  {
    id: "freelancer",
    name: "Freelancer Focus",
    slug: "freelancer",
    category: "Creative",
    description: "Highlights live project links, client list achievements, and visual rating dots.",
    atsScore: 89,
    popularity: 4.6,
    recommendedFor: ["Independent Contractors", "Freelancers", "Consultants"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "left-sidebar",
      fontFamily: "montserrat",
      primaryColor: "#059669",
      secondaryColor: "#374151",
      accentColor: "#10b981",
      backgroundColor: "#ffffff",
      borderRadius: "md",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "circle",
      headerStyle: "split",
      skillStyle: "dots",
      photoStyle: "rounded-square",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "startup-founder",
    name: "Startup Founder",
    slug: "startup-founder",
    category: "Executive",
    description: "Modern bold typography, highlights venture projects, metric bullet highlights, and skills categories.",
    atsScore: 92,
    popularity: 4.75,
    recommendedFor: ["Co-founders", "CEOs", "Venture Partners", "Consultants"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "sans",
      primaryColor: "#0f172a",
      secondaryColor: "#475569",
      accentColor: "#64748b",
      backgroundColor: "#ffffff",
      borderRadius: "md",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "simple",
      headerStyle: "banner",
      skillStyle: "categories",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "consultant",
    name: "Consultant Corporate",
    slug: "consultant",
    category: "Executive",
    description: "Highly polished two-column layout showing business achievements, timeline nodes, and gray badges.",
    atsScore: 91,
    popularity: 4.8,
    recommendedFor: ["Management Consultants", "Strategists", "Partners"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "two-column",
      fontFamily: "serif",
      primaryColor: "#475569",
      secondaryColor: "#334155",
      accentColor: "#64748b",
      backgroundColor: "#ffffff",
      borderRadius: "sm",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "square",
      headerStyle: "left-border",
      skillStyle: "badges",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "solid",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
  {
    id: "international-cv",
    name: "International Europass",
    slug: "international-cv",
    category: "Academic",
    description: "Follows strict multi-lingual guidelines, left contact panel details, and simple bullet list structures.",
    atsScore: 90,
    popularity: 4.7,
    recommendedFor: ["EU Jobs", "Global CVs", "Visas Applications"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "left-sidebar",
      fontFamily: "sans",
      primaryColor: "#003399", // Blue EU Flag color theme
      secondaryColor: "#555555",
      accentColor: "#ffcc00",
      backgroundColor: "#ffffff",
      borderRadius: "none",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "simple",
      headerStyle: "split",
      skillStyle: "dots",
      photoStyle: "square",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "sm",
      lineHeight: "normal",
    },
  },
  {
    id: "compact",
    name: "Compact High Density",
    slug: "compact",
    category: "ATS Friendly",
    description: "Extremely narrow padding margins (0.8cm) and line heights, designed to fit maximum content onto a single page.",
    atsScore: 98,
    popularity: 4.9,
    recommendedFor: ["Engineers with massive experience", "Academic CVs", "Researchers"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "sans",
      primaryColor: "#0f172a",
      secondaryColor: "#334155",
      accentColor: "#0284c7",
      backgroundColor: "#ffffff",
      borderRadius: "none",
      sectionSpacing: "compact",
      dividerStyle: "solid",
      iconStyle: "none",
      headerStyle: "compact",
      skillStyle: "text",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "compact",
      fontSize: "sm",
      lineHeight: "tight",
    },
  },
  {
    id: "elegant",
    name: "Elegant Serif Luxury",
    slug: "elegant",
    category: "Minimal",
    description: "Uses gorgeous Playfair Display headings, loose margins, and simple horizontal dividers.",
    atsScore: 91,
    popularity: 4.85,
    recommendedFor: ["Luxury Brands", "Legal Professionals", "Art Historians"],
    isPremium: true,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "playfair",
      primaryColor: "#4c0519", // Deep rose burgundy
      secondaryColor: "#4f4f4f",
      accentColor: "#9f1239",
      backgroundColor: "#fffdfa", // Creamy background
      borderRadius: "none",
      sectionSpacing: "spacious",
      dividerStyle: "solid",
      iconStyle: "none",
      headerStyle: "minimal",
      skillStyle: "text",
      photoStyle: "none",
      photoPosition: "center",
      timelineStyle: "none",
      pageMargin: "wide",
      fontSize: "lg",
      lineHeight: "loose",
    },
  },
  {
    id: "classic",
    name: "Classic Traditional",
    slug: "classic",
    category: "Professional",
    description: "The time-tested Harvard standard layout featuring traditional serif styles, margins, and section markers.",
    atsScore: 99,
    popularity: 4.9,
    recommendedFor: ["MBA Graduates", "Finance", "Legal Staff", "Accountants"],
    isPremium: false,
    defaultConfig: {
      layoutStyle: "single-column",
      fontFamily: "serif",
      primaryColor: "#000000",
      secondaryColor: "#333333",
      accentColor: "#111111",
      backgroundColor: "#ffffff",
      borderRadius: "none",
      sectionSpacing: "normal",
      dividerStyle: "solid",
      iconStyle: "none",
      headerStyle: "compact",
      skillStyle: "text",
      photoStyle: "none",
      photoPosition: "left",
      timelineStyle: "none",
      pageMargin: "normal",
      fontSize: "base",
      lineHeight: "normal",
    },
  },
];

export function getTemplateConfig(templateId: string): TemplateConfig {
  const match = templatesRegistry.find((t) => t.id === templateId);
  return match ? match.defaultConfig : templatesRegistry[0].defaultConfig;
}
